# Generated by Django 4.1.1 on 2023-07-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0003_mealoptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealoptions",
            name="is_additional",
            field=models.BooleanField(default=False),
        ),
    ]
