# Generated by Django 4.1.1 on 2023-07-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0004_mealoptions_is_additional"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderMealOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resturant_app.mealoptions",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resturant_app.order",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="hotelimages",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="hotelplans",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="restaurantopenbuffet",
            name="restaurant",
        ),
        migrations.DeleteModel(
            name="Hotel",
        ),
        migrations.DeleteModel(
            name="HotelImages",
        ),
        migrations.DeleteModel(
            name="HotelPlans",
        ),
        migrations.DeleteModel(
            name="RestaurantOpenBuffet",
        ),
    ]
