# Generated by Django 4.1.1 on 2023-07-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0005_ordermealoption_remove_hotelimages_hotel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("times_to_use", models.IntegerField()),
                ("used_times", models.IntegerField(default=0)),
            ],
        ),
    ]
