# Generated by Django 4.1.1 on 2023-07-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0006_promocode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "preparing"),
                    ("delivering", "delivering"),
                    ("delivered", "delivered"),
                    ("canceled", "canceled"),
                    ("is_paid", "is_paid"),
                ],
                max_length=50,
            ),
        ),
    ]
