# Generated by Django 4.1.1 on 2023-07-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "resturant_app",
            "0010_rename_restaurantopenbuffet_restaurantopenbuffetpackage_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderMeal",
            new_name="OrderItem",
        ),
        migrations.RenameModel(
            old_name="OrderMealOption",
            new_name="OrderItemOption",
        ),
    ]
