# Generated by Django 4.1.1 on 2023-07-21 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resturant_app", "0013_hotel_hotelplans_hotelimages_orderitem_hotel_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
