# Generated by Django 4.1.1 on 2023-07-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0014_hotel_admin"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HotelPlans",
            new_name="Hall",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="hotel_plan",
            new_name="hall",
        ),
    ]
