# Generated by Django 4.1.1 on 2023-07-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0017_promocode_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="media/"
            ),
        ),
        migrations.DeleteModel(
            name="HotelImages",
        ),
    ]
