# Generated by Django 4.1.1 on 2023-07-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0019_hallimages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hall",
            old_name="services",
            new_name="name",
        ),
        migrations.AddField(
            model_name="hall",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
