# Generated by Django 4.1.1 on 2023-07-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0020_rename_services_hall_name_hall_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HallOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=50)),
                ("price", models.IntegerField(default=0)),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resturant_app.hall",
                    ),
                ),
            ],
        ),
    ]
