# Generated by Django 4.1.1 on 2023-07-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0021_halloptions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RestaurantOpenBuffetPackage",
            new_name="OpenBuffetPackage",
        ),
    ]
