# Generated by Django 4.1.1 on 2023-07-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0022_rename_restaurantopenbuffetpackage_openbuffetpackage"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="media/"
            ),
        ),
        migrations.AddField(
            model_name="openbuffetpackage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resturant_app.category",
            ),
        ),
    ]
