# Generated by Django 4.1.1 on 2023-08-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0025_remove_hall_number_of_guests_hall_max_hall_min"),
    ]

    operations = [
        migrations.AddField(
            model_name="openbuffetpackage",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="openbuffetpackageoptions",
            name="price",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="description",
            field=models.TextField(),
        ),
    ]
