# Generated by Django 4.1.1 on 2023-10-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0030_alter_branch_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="description_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="description_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mealoptions",
            name="option_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="mealoptions",
            name="option_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="description_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="description_en",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
