# Generated by Django 4.1.1 on 2023-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0031_meal_description_ar_meal_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="name_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="name_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
