# Generated by Django 4.1.1 on 2023-11-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0032_meal_name_ar_meal_name_en_restaurant_name_ar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="delivery_fees",
            field=models.FloatField(default=0),
        ),
    ]
