# Generated by Django 4.1.1 on 2023-12-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0036_mealoptions_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="min_quantity",
            field=models.IntegerField(
                default=1, help_text="min quantity to add the meal to the cart"
            ),
        ),
    ]
