# Generated by Django 4.1.1 on 2023-12-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0037_meal_min_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="meal",
            name="name_ar",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="name_en",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name_ar",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name_en",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
