# Generated by Django 4.1.1 on 2023-12-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0038_alter_meal_name_alter_meal_name_ar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="description",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="meal",
            name="description_ar",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="description_en",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="description",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="description_ar",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="description_en",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
