# Generated by Django 4.1.1 on 2023-08-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addonsapp", "0004_category_image_promocode"),
        ("resturant_app", "0027_remove_hall_hotel_remove_hallimages_hall_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenBuffetPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("clients_count", models.IntegerField()),
                ("image", models.ImageField(upload_to="")),
                ("price", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addonsapp.category",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resturant_app.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpenBuffetPackageOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=50)),
                ("is_additional", models.BooleanField(default=False)),
                ("price", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openbuffet_app.openbuffetpackage",
                    ),
                ),
            ],
        ),
    ]
