# Generated by Django 4.1.1 on 2023-09-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openbuffet_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="openbuffetpackage",
            name="description",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
    ]
