# Generated by Django 4.1.1 on 2023-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openbuffet_app", "0003_openbuffetpackage_description_ar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="openbuffetpackage",
            name="name_ar",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="openbuffetpackage",
            name="name_en",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
