# Generated by Django 4.1.1 on 2023-12-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openbuffet_app", "0005_openbuffetpackageoptions_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openbuffetpackage",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="openbuffetpackage",
            name="name_ar",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="openbuffetpackage",
            name="name_en",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
