PENDING_PAYMENT = "pending_payment"
PENDING_CONFIRMATION = "pending_confirmation"
CONFIRMED = "confirmed"
PREPARING = "preparing"
DELIVERING = "delivering"
DELIVERED = "delivered"
READY_FOR_PICKUP = "ready_for_pickup"
CANCELLED = "cancelled"
ARRIVED_TO_RESTAURANT = "arrived_to_restaurant"
PICKED_ORDER = "picked_order"
ORDER_CHOICES = [
    (PENDING_PAYMENT, PENDING_PAYMENT),
    (PENDING_CONFIRMATION, PENDING_CONFIRMATION),
    (CONFIRMED, CONFIRMED),
    (PREPARING, PREPARING),
    (DELIVERING, DELIVERING),
    (DELIVERED, DELIVERED),
    (READY_FOR_PICKUP, READY_FOR_PICKUP),
    (CANCELLED, CANCELLED),
    (ARRIVED_TO_RESTAURANT, ARRIVED_TO_RESTAURANT),
    (PICKED_ORDER, PICKED_ORDER),
]
