# Generated by Django 4.1.1 on 2023-09-22 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0002_hotel_rate"),
        ("resturant_app", "0029_meal_is_top_dish"),
        ("order_app", "0005_alter_order_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel_app.hotel",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resturant_app.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "pending_payment"),
                    ("pending_confirmation", "pending_confirmation"),
                    ("confirmed", "confirmed"),
                    ("preparing", "preparing"),
                    ("delivering", "delivering"),
                    ("delivered", "delivered"),
                    ("ready_for_pickup", "ready_for_pickup"),
                    ("cancelled", "cancelled"),
                ],
                max_length=50,
            ),
        ),
    ]
