# Generated by Django 4.1.1 on 2023-09-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0007_remove_order_payment_type_remove_order_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
