# Generated by Django 4.1.1 on 2023-09-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0008_alter_order_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="note",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
