# Generated by Django 4.1.1 on 2023-09-29 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0029_meal_is_top_dish"),
        ("order_app", "0009_alter_orderitem_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="meal",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resturant_app.meal",
            ),
        ),
    ]
