# Generated by Django 4.1.1 on 2023-09-29 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0010_alter_orderitem_meal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitemoption",
            name="order",
        ),
        migrations.AddField(
            model_name="orderitemoption",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="order_app.orderitem",
            ),
        ),
    ]
