# Generated by Django 4.1.1 on 2023-10-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0012_order_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemoption",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
