# Generated by Django 4.1.1 on 2023-10-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0013_orderitemoption_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash_on_delivery", "cash_on_delivery"),
                    ("online_payment", "online_payment"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
