# Generated by Django 4.1.1 on 2023-10-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0014_order_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.IntegerField(default=0),
        ),
    ]
