# Generated by Django 4.1.1 on 2023-11-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0015_order_delivery_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gate_way_id",
            field=models.CharField(default="", max_length=50),
        ),
    ]
