# Generated by Django 4.1.1 on 2023-11-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0017_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="arrived_to_restaurant_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="begin_trip_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="picked_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="preparing_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="ready_to_delivery_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
