# Generated by Django 4.1.1 on 2023-11-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0034_branch_estimated_mins"),
        ("order_app", "0018_order_arrived_to_restaurant_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resturant_app.branch",
            ),
        ),
    ]
