# Generated by Django 4.1.1 on 2023-11-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0019_order_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="branch",
        ),
    ]
