# Generated by Django 4.1.1 on 2023-11-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0022_orderitemoption_hall_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "pending_payment"),
                    ("pending_confirmation", "pending_confirmation"),
                    ("confirmed", "confirmed"),
                    ("preparing", "preparing"),
                    ("delivering", "delivering"),
                    ("delivered", "delivered"),
                    ("ready_for_pickup", "ready_for_pickup"),
                    ("cancelled", "cancelled"),
                    ("arrived_to_restaurant", "arrived_to_restaurant"),
                    ("picked_order", "picked_order"),
                ],
                max_length=50,
            ),
        ),
    ]
