# Generated by Django 4.1.1 on 2023-12-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0023_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="has_sent_mony_to_driver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="has_sent_mony_to_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_details",
            field=models.TextField(default=None, null=True),
        ),
    ]
