# Generated by Django 4.1.1 on 2023-12-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0025_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="invoice_details",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
