# Generated by Django 4.1.1 on 2024-02-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0026_alter_order_invoice_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_rate", models.IntegerField()),
                ("delivery_rate", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_app.order",
                    ),
                ),
            ],
        ),
    ]
