# Generated by Django 4.1.1 on 2024-02-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0027_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="rates",
            name="comment",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
