# Generated by Django 4.1.1 on 2024-03-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0028_rates_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="daftra_invoice",
            field=models.URLField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
