# Generated by Django 4.1.1 on 2023-07-06 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="description",
        ),
        migrations.AddField(
            model_name="address",
            name="apartment",
            field=models.CharField(default=" ", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="building",
            field=models.CharField(default=" ", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="floor",
            field=models.CharField(default=" ", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="location",
            field=models.CharField(default=" ", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="phone",
            field=models.CharField(default=" ", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="street",
            field=models.CharField(default=" ", max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DeliveryCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("plat", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
