# Generated by Django 4.1.1 on 2023-08-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0004_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
    ]
