# Generated by Django 4.1.1 on 2023-10-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0008_alter_address_apartment_alter_address_building_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("delivery", "delivery"),
                    ("client", "client"),
                    ("manager", "manager"),
                ],
                default="client",
                max_length=50,
            ),
        ),
    ]
