# Generated by Django 4.1.1 on 2023-11-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0010_deliverycar_model_ar_deliverycar_model_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
