# Generated by Django 4.1.1 on 2023-11-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0011_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="new_phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Phone"
            ),
        ),
    ]
