# Generated by Django 4.1.1 on 2023-12-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0012_user_new_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
