# Generated by Django 4.1.1 on 2024-01-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0013_alter_address_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="loyalty_points",
            field=models.IntegerField(default=0),
        ),
    ]
