# Generated by Django 4.1.1 on 2024-03-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0012_alter_hotel_admin"),
        ("resturant_app", "0040_alter_restaurant_admin"),
        ("userapp", "0015_user_daftra_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_hotel",
                to="hotel_app.hotel",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_restaurant",
                to="resturant_app.restaurant",
            ),
        ),
    ]
