# Generated by Django 4.1.1 on 2023-07-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addonsapp", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("instagram", models.URLField(max_length=500)),
                ("twitter", models.URLField(max_length=500)),
                ("facebook", models.URLField(max_length=500)),
                ("snapchat", models.URLField(max_length=500)),
                ("whatsapp", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("photo", models.ImageField(upload_to="media/")),
                ("description", models.CharField(max_length=50)),
                ("link", models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="TermsAndConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
    ]
