# Generated by Django 4.1.1 on 2023-08-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addonsapp", "0004_category_image_promocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
