# Generated by Django 4.1.1 on 2023-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addonsapp", "0008_category_name_ar_category_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="text_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="about",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="ads",
            name="description_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ads",
            name="description_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ads",
            name="name_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ads",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="text_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="termsandconditions",
            name="text_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="termsandconditions",
            name="text_en",
            field=models.TextField(null=True),
        ),
    ]
