# Generated by Django 4.1.1 on 2023-11-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resturant_app", "0035_meal_is_share_box"),
        ("hotel_app", "0008_hallavailabletime_name_ar_hallavailabletime_name_en"),
        ("addonsapp", "0009_about_text_ar_about_text_en_ads_description_ar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "required_quantity",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_app.hotel",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resturant_app.restaurant",
                    ),
                ),
            ],
        ),
    ]
