# Generated by Django 4.1.1 on 2023-11-13 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0009_halloptions_category"),
        ("resturant_app", "0036_mealoptions_category"),
        ("addonsapp", "0010_optionscategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionscategory",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel_app.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="optionscategory",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resturant_app.restaurant",
            ),
        ),
    ]
