# Generated by Django 4.1.1 on 2023-11-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addonsapp", "0011_alter_optionscategory_hotel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="optionscategory",
            name="name_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="optionscategory",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
