# Generated by Django 4.1.1 on 2023-11-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addonsapp", "0012_optionscategory_name_ar_optionscategory_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="is_send_msg",
            field=models.BooleanField(default=False),
        ),
    ]
