# Generated by Django 4.1.1 on 2023-12-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "addonsapp",
            "0014_alter_ads_name_alter_ads_name_ar_alter_ads_name_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="description",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="ads",
            name="description_ar",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="ads",
            name="description_en",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
