# Generated by Django 4.1.1 on 2024-01-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addonsapp", "0016_loyaltypointspromocode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
