# Generated by Django 4.1.1 on 2023-10-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0003_hotel_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="HallAvailableTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "Hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel_app.hall"
                    ),
                ),
            ],
        ),
    ]
