# Generated by Django 4.1.1 on 2023-11-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0005_hall_description_ar_hall_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hallavailabletime",
            name="name",
            field=models.CharField(default=" ", max_length=50),
            preserve_default=False,
        ),
    ]
