# Generated by Django 4.1.1 on 2023-11-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0007_hall_name_ar_hall_name_en_hotel_address_ar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hallavailabletime",
            name="name_ar",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="hallavailabletime",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
