# Generated by Django 4.1.1 on 2023-11-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addonsapp", "0010_optionscategory"),
        ("hotel_app", "0008_hallavailabletime_name_ar_hallavailabletime_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="halloptions",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="addonsapp.optionscategory",
            ),
        ),
    ]
