# Generated by Django 4.1.1 on 2023-11-15 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0009_halloptions_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="HallBusyDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "Hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel_app.hall"
                    ),
                ),
            ],
        ),
    ]
