# Generated by Django 4.1.1 on 2023-12-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0010_hallbusydate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="hall",
            name="name_ar",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="hall",
            name="name_en",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="hallavailabletime",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="hallavailabletime",
            name="name_ar",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="hallavailabletime",
            name="name_en",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name_ar",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name_en",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
