# Generated by Django 4.1.1 on 2024-03-23 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hotel_app", "0011_alter_hall_name_alter_hall_name_ar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotel_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
