# Generated by Django 4.1.1 on 2024-01-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificationapp", "0003_updatedbulknotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="updatedexpodevice",
            name="type",
            field=models.CharField(
                choices=[("driver", "driver"), ("customer", "customer")],
                default="customer",
                max_length=50,
            ),
        ),
    ]
